name: Build Frontend
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Show repository root structure
        run: ls -la
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm install
        working-directory: model-management-system/frontend
      
      - name: Build
        run: npm run build
        working-directory: model-management-system/frontend
      
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: model-management-system/frontend/dist
