name: Pack Node Modules for Windows

on:
  workflow_dispatch:

jobs:
  pack:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install   # 改为 install，自动生成 lock 文件

      - name: Remove .git folder
        run: if (Test-Path .git) { Remove-Item .git -Recurse -Force }

      - name: Upload entire project as artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-with-node-modules
          path: .
